### ISSUE TITLE
Update Organizations.json on brigade.codeforameria.org

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/project-template#2]
Update the CfA brigade API with more up to date organizations info

https://github.com/BetaNYC/brigade-information

**Comment by tommy-stone** [comment]
Updated organization.json and removed rss feed (we currently do not have one). All other information was up to date. Waiting for merge from code for america.

**Comment by nikolajbaer** [comment]
Ok @tommy-stone i added you and the core team to be project admins

**Comment by tommy-stone** [comment]
Confirmed that information is up to date.
