### ISSUE TITLE
Add Civic.json to all active projects

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/project-template#3]
Add civic.json to projects that are currently active ,e.g. tacos/transit and mealscount

Reference for civic.json:

https://github.com/codeforamerica/cfapi

**Comment by tommy-stone** [comment]
Created civic.json file for all open projects. tacos-in-transit, BikeSD and mealscount have a pull request because I do not have write access. Waiting for maintainers to merge

**Comment by tommy-stone** [comment]
This will be used for newer projects. Closing issue
