### ISSUE TITLE
Create deck for Pitching to UX Speakeasy November 6th

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/project-template#6]
Generate deck and fill in details about projects and needs for UX help

**Comment by nikolajbaer** [comment]
Pitch Deck:
https://docs.google.com/presentation/d/1PHzj0GtnETCfhMaq_Q8tEHtzXRJJNURPMFFxOlpches/edit#slide=id.p

**Comment by tommy-stone** [comment]
Added SD Voter's Voice portion for slides

**Comment by tommy-stone** [comment]
Pitch completed, items added
